# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsdialog.ui'
#
# Created: Sun Feb 17 21:07:04 2013
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SettingsDialogBaseClass(object):
    def setupUi(self, SettingsDialogBaseClass):
        SettingsDialogBaseClass.setObjectName(_fromUtf8("SettingsDialogBaseClass"))
        SettingsDialogBaseClass.resize(581, 329)
        SettingsDialogBaseClass.setWindowTitle(QtGui.QApplication.translate("SettingsDialogBaseClass", "3DLP Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(SettingsDialogBaseClass)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.groupBox_2 = QtGui.QGroupBox(SettingsDialogBaseClass)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("SettingsDialogBaseClass", "Printing Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.enableprintercontrol = QtGui.QCheckBox(self.groupBox_2)
        self.enableprintercontrol.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "Enable Printer Control?", None, QtGui.QApplication.UnicodeUTF8))
        self.enableprintercontrol.setChecked(False)
        self.enableprintercontrol.setObjectName(_fromUtf8("enableprintercontrol"))
        self.verticalLayout.addWidget(self.enableprintercontrol)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radio_arduinoUno = QtGui.QRadioButton(self.groupBox_2)
        self.radio_arduinoUno.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "Arduino Uno", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_arduinoUno.setChecked(True)
        self.radio_arduinoUno.setObjectName(_fromUtf8("radio_arduinoUno"))
        self.horizontalLayout_4.addWidget(self.radio_arduinoUno)
        self.radio_arduinoMega = QtGui.QRadioButton(self.groupBox_2)
        self.radio_arduinoMega.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "Arduino Mega", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_arduinoMega.setObjectName(_fromUtf8("radio_arduinoMega"))
        self.horizontalLayout_4.addWidget(self.radio_arduinoMega)
        self.radio_pyMCU = QtGui.QRadioButton(self.groupBox_2)
        self.radio_pyMCU.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "PyMCU", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_pyMCU.setObjectName(_fromUtf8("radio_pyMCU"))
        self.horizontalLayout_4.addWidget(self.radio_pyMCU)
        self.radio_ramps = QtGui.QRadioButton(self.groupBox_2)
        self.radio_ramps.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "RAMPS", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_ramps.setObjectName(_fromUtf8("radio_ramps"))
        self.horizontalLayout_4.addWidget(self.radio_ramps)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_29 = QtGui.QLabel(self.groupBox_2)
        self.label_29.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_3.addWidget(self.label_29)
        self.pickcom = QtGui.QComboBox(self.groupBox_2)
        self.pickcom.setObjectName(_fromUtf8("pickcom"))
        self.horizontalLayout_3.addWidget(self.pickcom)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "Baud:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_3.addWidget(self.label_24)
        self.printerbaud = QtGui.QComboBox(self.groupBox_2)
        self.printerbaud.setObjectName(_fromUtf8("printerbaud"))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(0, QtGui.QApplication.translate("SettingsDialogBaseClass", "115200", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(1, QtGui.QApplication.translate("SettingsDialogBaseClass", "57600", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(2, QtGui.QApplication.translate("SettingsDialogBaseClass", "38400", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(3, QtGui.QApplication.translate("SettingsDialogBaseClass", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(4, QtGui.QApplication.translate("SettingsDialogBaseClass", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(5, QtGui.QApplication.translate("SettingsDialogBaseClass", "4800", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(6, QtGui.QApplication.translate("SettingsDialogBaseClass", "2400", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_3.addWidget(self.printerbaud)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "Remote Host Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.remote_port = QtGui.QLineEdit(self.groupBox_2)
        self.remote_port.setEnabled(False)
        self.remote_port.setText(_fromUtf8(""))
        self.remote_port.setObjectName(_fromUtf8("remote_port"))
        self.horizontalLayout_5.addWidget(self.remote_port)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "Exposure Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_20.addWidget(self.label_6)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.exposure_time = QtGui.QLineEdit(self.groupBox_2)
        self.exposure_time.setText(_fromUtf8(""))
        self.exposure_time.setObjectName(_fromUtf8("exposure_time"))
        self.horizontalLayout_6.addWidget(self.exposure_time)
        self.label_28 = QtGui.QLabel(self.groupBox_2)
        self.label_28.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_6.addWidget(self.label_28)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_26 = QtGui.QLabel(self.groupBox_2)
        self.label_26.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "Number of starting layers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_8.addWidget(self.label_26)
        self.starting_layers = QtGui.QLineEdit(self.groupBox_2)
        self.starting_layers.setText(_fromUtf8(""))
        self.starting_layers.setObjectName(_fromUtf8("starting_layers"))
        self.horizontalLayout_8.addWidget(self.starting_layers)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_27 = QtGui.QLabel(self.groupBox_2)
        self.label_27.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "Starting layer exposure ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_9.addWidget(self.label_27)
        self.starting_layer_exposure = QtGui.QLineEdit(self.groupBox_2)
        self.starting_layer_exposure.setText(_fromUtf8(""))
        self.starting_layer_exposure.setObjectName(_fromUtf8("starting_layer_exposure"))
        self.horizontalLayout_9.addWidget(self.starting_layer_exposure)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.enableslideshow = QtGui.QCheckBox(self.groupBox_2)
        self.enableslideshow.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "Slideshow enabled?", None, QtGui.QApplication.UnicodeUTF8))
        self.enableslideshow.setChecked(False)
        self.enableslideshow.setObjectName(_fromUtf8("enableslideshow"))
        self.verticalLayout.addWidget(self.enableslideshow)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_25 = QtGui.QLabel(self.groupBox_2)
        self.label_25.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "Choose monitor to print on:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_10.addWidget(self.label_25)
        self.pickscreen = QtGui.QComboBox(self.groupBox_2)
        self.pickscreen.setObjectName(_fromUtf8("pickscreen"))
        self.horizontalLayout_10.addWidget(self.pickscreen)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_12.addLayout(self.verticalLayout)
        self.horizontalLayout_13.addWidget(self.groupBox_2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(SettingsDialogBaseClass)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("SettingsDialogBaseClass", "Projector Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.projectorcontrol = QtGui.QCheckBox(self.groupBox_3)
        self.projectorcontrol.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "Enable Projector Control?", None, QtGui.QApplication.UnicodeUTF8))
        self.projectorcontrol.setChecked(False)
        self.projectorcontrol.setObjectName(_fromUtf8("projectorcontrol"))
        self.verticalLayout_6.addWidget(self.projectorcontrol)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "COM Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_5.addWidget(self.label_16)
        self.projector_pickcom = QtGui.QComboBox(self.groupBox_3)
        self.projector_pickcom.setObjectName(_fromUtf8("projector_pickcom"))
        self.verticalLayout_5.addWidget(self.projector_pickcom)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "Serial Baud rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_14.addWidget(self.label_17)
        self.projector_baud = QtGui.QComboBox(self.groupBox_3)
        self.projector_baud.setObjectName(_fromUtf8("projector_baud"))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(0, QtGui.QApplication.translate("SettingsDialogBaseClass", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(1, QtGui.QApplication.translate("SettingsDialogBaseClass", "115200", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(2, QtGui.QApplication.translate("SettingsDialogBaseClass", "57600", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(3, QtGui.QApplication.translate("SettingsDialogBaseClass", "38400", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(4, QtGui.QApplication.translate("SettingsDialogBaseClass", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(5, QtGui.QApplication.translate("SettingsDialogBaseClass", "4800", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(6, QtGui.QApplication.translate("SettingsDialogBaseClass", "2400", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_14.addWidget(self.projector_baud)
        self.horizontalLayout_11.addLayout(self.verticalLayout_14)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "Power Off Command:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_18.addWidget(self.label_21)
        self.projector_poweroffcommand = QtGui.QLineEdit(self.groupBox_3)
        self.projector_poweroffcommand.setMinimumSize(QtCore.QSize(200, 0))
        self.projector_poweroffcommand.setText(_fromUtf8(""))
        self.projector_poweroffcommand.setObjectName(_fromUtf8("projector_poweroffcommand"))
        self.verticalLayout_18.addWidget(self.projector_poweroffcommand)
        self.verticalLayout_6.addLayout(self.verticalLayout_18)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(SettingsDialogBaseClass)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox.setTitle(QtGui.QApplication.translate("SettingsDialogBaseClass", "Layer Advance Scripting", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.zscript = QtGui.QPlainTextEdit(self.groupBox)
        self.zscript.setObjectName(_fromUtf8("zscript"))
        self.horizontalLayout_7.addWidget(self.zscript)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_13.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButton = QtGui.QPushButton(SettingsDialogBaseClass)
        self.pushButton.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "Apply Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_3 = QtGui.QPushButton(SettingsDialogBaseClass)
        self.pushButton_3.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "Save Settings to Config File", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtGui.QPushButton(SettingsDialogBaseClass)
        self.pushButton_2.setText(QtGui.QApplication.translate("SettingsDialogBaseClass", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_14.addLayout(self.verticalLayout_3)

        self.retranslateUi(SettingsDialogBaseClass)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsDialogBaseClass.reject)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsDialogBaseClass.ApplySettings)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialogBaseClass)

    def retranslateUi(self, SettingsDialogBaseClass):
        pass

