# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manual_control_gui.ui'
#
# Created: Sat May 04 18:28:51 2013
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Manual_Control(object):
    def setupUi(self, Manual_Control):
        Manual_Control.setObjectName(_fromUtf8("Manual_Control"))
        Manual_Control.resize(374, 403)
        Manual_Control.setWindowTitle(QtGui.QApplication.translate("Manual_Control", "3DLP Manual Printer Control", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(Manual_Control)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label = QtGui.QLabel(Manual_Control)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setText(QtGui.QApplication.translate("Manual_Control", "Manual Printer Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_6.addWidget(self.label)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox = QtGui.QGroupBox(Manual_Control)
        self.groupBox.setTitle(QtGui.QApplication.translate("Manual_Control", "Z Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.Z_10 = QtGui.QRadioButton(self.groupBox)
        self.Z_10.setText(QtGui.QApplication.translate("Manual_Control", "10mm", None, QtGui.QApplication.UnicodeUTF8))
        self.Z_10.setObjectName(_fromUtf8("Z_10"))
        self.verticalLayout.addWidget(self.Z_10)
        self.Z_1 = QtGui.QRadioButton(self.groupBox)
        self.Z_1.setText(QtGui.QApplication.translate("Manual_Control", "1mm", None, QtGui.QApplication.UnicodeUTF8))
        self.Z_1.setObjectName(_fromUtf8("Z_1"))
        self.verticalLayout.addWidget(self.Z_1)
        self.Z_01 = QtGui.QRadioButton(self.groupBox)
        self.Z_01.setText(QtGui.QApplication.translate("Manual_Control", "0.1mm", None, QtGui.QApplication.UnicodeUTF8))
        self.Z_01.setObjectName(_fromUtf8("Z_01"))
        self.verticalLayout.addWidget(self.Z_01)
        self.Z_001 = QtGui.QRadioButton(self.groupBox)
        self.Z_001.setText(QtGui.QApplication.translate("Manual_Control", "0.01mm", None, QtGui.QApplication.UnicodeUTF8))
        self.Z_001.setChecked(False)
        self.Z_001.setObjectName(_fromUtf8("Z_001"))
        self.verticalLayout.addWidget(self.Z_001)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setText(_fromUtf8(""))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.horizontalLayout_5.addWidget(self.radioButton)
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setText(QtGui.QApplication.translate("Manual_Control", "steps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.toolButton = QtGui.QToolButton(self.groupBox)
        self.toolButton.setText(QtGui.QApplication.translate("Manual_Control", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/nav_up_blue.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(48, 48))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.verticalLayout_2.addWidget(self.toolButton)
        self.toolButton_4 = QtGui.QToolButton(self.groupBox)
        self.toolButton_4.setText(QtGui.QApplication.translate("Manual_Control", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/nav_down_blue.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon1)
        self.toolButton_4.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.verticalLayout_2.addWidget(self.toolButton_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(15, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setText(QtGui.QApplication.translate("Manual_Control", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.DRO_Z = QtGui.QLCDNumber(self.groupBox)
        self.DRO_Z.setMinimumSize(QtCore.QSize(100, 20))
        self.DRO_Z.setSmallDecimalPoint(False)
        self.DRO_Z.setNumDigits(8)
        self.DRO_Z.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.DRO_Z.setProperty("value", 0.0)
        self.DRO_Z.setObjectName(_fromUtf8("DRO_Z"))
        self.horizontalLayout_3.addWidget(self.DRO_Z)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setText(QtGui.QApplication.translate("Manual_Control", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setText(QtGui.QApplication.translate("Manual_Control", "Zero Z Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_3.addWidget(self.pushButton)
        self.line_3 = QtGui.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_3.addWidget(self.line_3)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox)
        self.pushButton_3.setText(QtGui.QApplication.translate("Manual_Control", "Fast Up", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_9.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.groupBox)
        self.pushButton_4.setText(QtGui.QApplication.translate("Manual_Control", "Fast Down", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_9.addWidget(self.pushButton_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.pushButton_5 = QtGui.QPushButton(self.groupBox)
        self.pushButton_5.setText(QtGui.QApplication.translate("Manual_Control", "Home Z Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.verticalLayout_7.addWidget(self.pushButton_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_7)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_2 = QtGui.QGroupBox(Manual_Control)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Manual_Control", "X Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.toolButton_2 = QtGui.QToolButton(self.groupBox_2)
        self.toolButton_2.setGeometry(QtCore.QRect(11, 24, 130, 54))
        self.toolButton_2.setText(QtGui.QApplication.translate("Manual_Control", "Trigger X Axis", None, QtGui.QApplication.UnicodeUTF8))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/nav_right_blue.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon2)
        self.toolButton_2.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.verticalLayout_5.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.line_4 = QtGui.QFrame(Manual_Control)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_6.addWidget(self.line_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.toolButton_3 = QtGui.QToolButton(Manual_Control)
        self.toolButton_3.setText(QtGui.QApplication.translate("Manual_Control", "Stop Motion", None, QtGui.QApplication.UnicodeUTF8))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon3)
        self.toolButton_3.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.horizontalLayout_7.addWidget(self.toolButton_3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)

        self.retranslateUi(Manual_Control)
        QtCore.QObject.connect(self.toolButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Manual_Control.Z_up)
        QtCore.QObject.connect(self.toolButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), Manual_Control.Z_down)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Manual_Control.Zero_Z)
        QtCore.QObject.connect(self.toolButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Manual_Control.X_up)
        QtCore.QMetaObject.connectSlotsByName(Manual_Control)

    def retranslateUi(self, Manual_Control):
        pass

import resource_rc
