# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '3dlp.ui'
#
# Created: Thu May 24 23:41:30 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 768)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 162, 162))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 162, 162))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 162, 162))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 162, 162))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "3dlp", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(720, 10, 281, 311))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 261, 281))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Printing Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(10, 120, 241, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 31, 16))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.line_2 = QtGui.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(10, 170, 241, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.remote_port = QtGui.QLineEdit(self.groupBox)
        self.remote_port.setGeometry(QtCore.QRect(120, 100, 101, 20))
        self.remote_port.setText(QtGui.QApplication.translate("MainWindow", "4000", None, QtGui.QApplication.UnicodeUTF8))
        self.remote_port.setObjectName(_fromUtf8("remote_port"))
        self.exposure_time = QtGui.QLineEdit(self.groupBox)
        self.exposure_time.setGeometry(QtCore.QRect(10, 150, 81, 20))
        self.exposure_time.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.exposure_time.setObjectName(_fromUtf8("exposure_time"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 81, 16))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Exposure Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(100, 150, 46, 13))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.starting_layers = QtGui.QLineEdit(self.groupBox)
        self.starting_layers.setGeometry(QtCore.QRect(10, 200, 41, 20))
        self.starting_layers.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.starting_layers.setObjectName(_fromUtf8("starting_layers"))
        self.starting_layer_exposure = QtGui.QLineEdit(self.groupBox)
        self.starting_layer_exposure.setGeometry(QtCore.QRect(150, 200, 81, 20))
        self.starting_layer_exposure.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.starting_layer_exposure.setObjectName(_fromUtf8("starting_layer_exposure"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 180, 131, 16))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Number of starting layers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(140, 180, 121, 16))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Starting layer exposure ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 91, 20))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Remote Host Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.printerbaud = QtGui.QComboBox(self.groupBox)
        self.printerbaud.setGeometry(QtCore.QRect(180, 20, 69, 22))
        self.printerbaud.setObjectName(_fromUtf8("printerbaud"))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(0, QtGui.QApplication.translate("MainWindow", "115200", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(1, QtGui.QApplication.translate("MainWindow", "57600", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(2, QtGui.QApplication.translate("MainWindow", "38400", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(3, QtGui.QApplication.translate("MainWindow", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(4, QtGui.QApplication.translate("MainWindow", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(5, QtGui.QApplication.translate("MainWindow", "4800", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(6, QtGui.QApplication.translate("MainWindow", "2400", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(150, 20, 31, 16))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Baud:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.pickcom = QtGui.QComboBox(self.groupBox)
        self.pickcom.setGeometry(QtCore.QRect(40, 20, 91, 22))
        self.pickcom.setObjectName(_fromUtf8("pickcom"))
        self.enableprintercontrol = QtGui.QCheckBox(self.groupBox)
        self.enableprintercontrol.setGeometry(QtCore.QRect(20, 60, 141, 17))
        self.enableprintercontrol.setText(QtGui.QApplication.translate("MainWindow", "Enable Printer Control?", None, QtGui.QApplication.UnicodeUTF8))
        self.enableprintercontrol.setChecked(True)
        self.enableprintercontrol.setObjectName(_fromUtf8("enableprintercontrol"))
        self.radio_pymcu = QtGui.QRadioButton(self.groupBox)
        self.radio_pymcu.setGeometry(QtCore.QRect(170, 50, 82, 17))
        self.radio_pymcu.setText(QtGui.QApplication.translate("MainWindow", "PyMCU", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_pymcu.setChecked(False)
        self.radio_pymcu.setObjectName(_fromUtf8("radio_pymcu"))
        self.radio_arduino = QtGui.QRadioButton(self.groupBox)
        self.radio_arduino.setGeometry(QtCore.QRect(170, 70, 82, 17))
        self.radio_arduino.setText(QtGui.QApplication.translate("MainWindow", "Arduino", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_arduino.setCheckable(True)
        self.radio_arduino.setChecked(True)
        self.radio_arduino.setObjectName(_fromUtf8("radio_arduino"))
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(20, 250, 141, 16))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Choose monitor to print on:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.pickscreen = QtGui.QComboBox(self.groupBox)
        self.pickscreen.setGeometry(QtCore.QRect(160, 250, 61, 22))
        self.pickscreen.setObjectName(_fromUtf8("pickscreen"))
        self.enableslideshow = QtGui.QCheckBox(self.groupBox)
        self.enableslideshow.setGeometry(QtCore.QRect(20, 230, 121, 17))
        self.enableslideshow.setText(QtGui.QApplication.translate("MainWindow", "Slideshow enabled?", None, QtGui.QApplication.UnicodeUTF8))
        self.enableslideshow.setChecked(True)
        self.enableslideshow.setObjectName(_fromUtf8("enableslideshow"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 261, 281))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Slicing Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.image_height = QtGui.QLineEdit(self.groupBox_2)
        self.image_height.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.image_height.setText(QtGui.QApplication.translate("MainWindow", "800", None, QtGui.QApplication.UnicodeUTF8))
        self.image_height.setObjectName(_fromUtf8("image_height"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Image Height", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(130, 20, 81, 16))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Image Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.image_width = QtGui.QLineEdit(self.groupBox_2)
        self.image_width.setGeometry(QtCore.QRect(130, 40, 113, 20))
        self.image_width.setText(QtGui.QApplication.translate("MainWindow", "800", None, QtGui.QApplication.UnicodeUTF8))
        self.image_width.setObjectName(_fromUtf8("image_width"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Layer Thickness", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.layer_thickness = QtGui.QLineEdit(self.groupBox_2)
        self.layer_thickness.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.layer_thickness.setText(QtGui.QApplication.translate("MainWindow", ".001", None, QtGui.QApplication.UnicodeUTF8))
        self.layer_thickness.setObjectName(_fromUtf8("layer_thickness"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(150, 70, 71, 16))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Slicing Plane", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.slicing_plane = QtGui.QComboBox(self.groupBox_2)
        self.slicing_plane.setGeometry(QtCore.QRect(150, 90, 69, 22))
        self.slicing_plane.setObjectName(_fromUtf8("slicing_plane"))
        self.slicing_plane.addItem(_fromUtf8(""))
        self.slicing_plane.setItemText(0, QtGui.QApplication.translate("MainWindow", "XZ", None, QtGui.QApplication.UnicodeUTF8))
        self.slicing_plane.addItem(_fromUtf8(""))
        self.slicing_plane.setItemText(1, QtGui.QApplication.translate("MainWindow", "XY", None, QtGui.QApplication.UnicodeUTF8))
        self.slicing_plane.addItem(_fromUtf8(""))
        self.slicing_plane.setItemText(2, QtGui.QApplication.translate("MainWindow", "YZ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 120, 241, 111))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Z Options", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.z_options_start = QtGui.QLineEdit(self.groupBox_7)
        self.z_options_start.setGeometry(QtCore.QRect(90, 20, 113, 20))
        self.z_options_start.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.z_options_start.setObjectName(_fromUtf8("z_options_start"))
        self.label_13 = QtGui.QLabel(self.groupBox_7)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Starting Depth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_22 = QtGui.QLabel(self.groupBox_7)
        self.label_22.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Ending Depth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.groupBox_7)
        self.label_23.setGeometry(QtCore.QRect(10, 80, 101, 16))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Z slicing increment:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.z_options_end = QtGui.QLineEdit(self.groupBox_7)
        self.z_options_end.setGeometry(QtCore.QRect(90, 50, 113, 20))
        self.z_options_end.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.z_options_end.setObjectName(_fromUtf8("z_options_end"))
        self.z_options_increment = QtGui.QLineEdit(self.groupBox_7)
        self.z_options_increment.setGeometry(QtCore.QRect(110, 80, 113, 20))
        self.z_options_increment.setText(QtGui.QApplication.translate("MainWindow", ".01", None, QtGui.QApplication.UnicodeUTF8))
        self.z_options_increment.setObjectName(_fromUtf8("z_options_increment"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 590, 671, 121))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.scrollArea = QtGui.QScrollArea(self.groupBox_3)
        self.scrollArea.setGeometry(QtCore.QRect(10, 20, 651, 91))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 649, 89))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.consoletext = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.consoletext.setGeometry(QtCore.QRect(0, 0, 651, 91))
        self.consoletext.setReadOnly(True)
        self.consoletext.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.consoletext.setObjectName(_fromUtf8("consoletext"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 10, 671, 531))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.imagepreview = QtGui.QLabel(self.groupBox_4)
        self.imagepreview.setGeometry(QtCore.QRect(10, 20, 651, 511))
        self.imagepreview.setText(QtGui.QApplication.translate("MainWindow", "Image Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.imagepreview.setAlignment(QtCore.Qt.AlignCenter)
        self.imagepreview.setObjectName(_fromUtf8("imagepreview"))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(130, 560, 75, 23))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Slice only ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 560, 75, 23))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "Slice and Print", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(220, 560, 75, 23))
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "Print only", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(720, 330, 281, 51))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "File to slice:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.toolButton = QtGui.QToolButton(self.groupBox_5)
        self.toolButton.setGeometry(QtCore.QRect(250, 20, 25, 19))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.displayfilenamelabel = QtGui.QLineEdit(self.groupBox_5)
        self.displayfilenamelabel.setGeometry(QtCore.QRect(10, 20, 241, 20))
        self.displayfilenamelabel.setText(_fromUtf8(""))
        self.displayfilenamelabel.setReadOnly(False)
        self.displayfilenamelabel.setObjectName(_fromUtf8("displayfilenamelabel"))
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(720, 390, 291, 91))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Custom Z-axis command", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.zscript = QtGui.QPlainTextEdit(self.groupBox_6)
        self.zscript.setGeometry(QtCore.QRect(10, 20, 271, 61))
        self.zscript.setPlainText(_fromUtf8(""))
        self.zscript.setObjectName(_fromUtf8("zscript"))
        self.projectorsettings = QtGui.QGroupBox(self.centralwidget)
        self.projectorsettings.setGeometry(QtCore.QRect(720, 510, 291, 201))
        self.projectorsettings.setTitle(QtGui.QApplication.translate("MainWindow", "Projector Control Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.projectorsettings.setObjectName(_fromUtf8("projectorsettings"))
        self.projector_pickcom = QtGui.QComboBox(self.projectorsettings)
        self.projector_pickcom.setGeometry(QtCore.QRect(10, 40, 91, 22))
        self.projector_pickcom.setObjectName(_fromUtf8("projector_pickcom"))
        self.label_16 = QtGui.QLabel(self.projectorsettings)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "COM Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.projector_baud = QtGui.QComboBox(self.projectorsettings)
        self.projector_baud.setGeometry(QtCore.QRect(130, 40, 69, 22))
        self.projector_baud.setObjectName(_fromUtf8("projector_baud"))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(0, QtGui.QApplication.translate("MainWindow", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(1, QtGui.QApplication.translate("MainWindow", "115200", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(2, QtGui.QApplication.translate("MainWindow", "57600", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(3, QtGui.QApplication.translate("MainWindow", "38400", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(4, QtGui.QApplication.translate("MainWindow", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(5, QtGui.QApplication.translate("MainWindow", "4800", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(6, QtGui.QApplication.translate("MainWindow", "2400", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17 = QtGui.QLabel(self.projectorsettings)
        self.label_17.setGeometry(QtCore.QRect(130, 20, 91, 16))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Serial Baud rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.projector_parity = QtGui.QComboBox(self.projectorsettings)
        self.projector_parity.setGeometry(QtCore.QRect(10, 90, 69, 22))
        self.projector_parity.setObjectName(_fromUtf8("projector_parity"))
        self.projector_parity.addItem(_fromUtf8(""))
        self.projector_parity.setItemText(0, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_parity.addItem(_fromUtf8(""))
        self.projector_parity.setItemText(1, QtGui.QApplication.translate("MainWindow", "Even", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_parity.addItem(_fromUtf8(""))
        self.projector_parity.setItemText(2, QtGui.QApplication.translate("MainWindow", "Odd", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_parity.addItem(_fromUtf8(""))
        self.projector_parity.setItemText(3, QtGui.QApplication.translate("MainWindow", "Mark", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_parity.addItem(_fromUtf8(""))
        self.projector_parity.setItemText(4, QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18 = QtGui.QLabel(self.projectorsettings)
        self.label_18.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Parity:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.projector_databits = QtGui.QComboBox(self.projectorsettings)
        self.projector_databits.setGeometry(QtCore.QRect(100, 90, 69, 22))
        self.projector_databits.setObjectName(_fromUtf8("projector_databits"))
        self.projector_databits.addItem(_fromUtf8(""))
        self.projector_databits.setItemText(0, QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_databits.addItem(_fromUtf8(""))
        self.projector_databits.setItemText(1, QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_databits.addItem(_fromUtf8(""))
        self.projector_databits.setItemText(2, QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_databits.addItem(_fromUtf8(""))
        self.projector_databits.setItemText(3, QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19 = QtGui.QLabel(self.projectorsettings)
        self.label_19.setGeometry(QtCore.QRect(100, 70, 91, 16))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Data Bits:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.projector_stopbits = QtGui.QComboBox(self.projectorsettings)
        self.projector_stopbits.setGeometry(QtCore.QRect(190, 90, 69, 22))
        self.projector_stopbits.setObjectName(_fromUtf8("projector_stopbits"))
        self.projector_stopbits.addItem(_fromUtf8(""))
        self.projector_stopbits.setItemText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_stopbits.addItem(_fromUtf8(""))
        self.projector_stopbits.setItemText(1, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20 = QtGui.QLabel(self.projectorsettings)
        self.label_20.setGeometry(QtCore.QRect(190, 70, 91, 16))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Stop Bits:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.projector_poweroffcommand = QtGui.QLineEdit(self.projectorsettings)
        self.projector_poweroffcommand.setGeometry(QtCore.QRect(10, 140, 271, 20))
        self.projector_poweroffcommand.setText(QtGui.QApplication.translate("MainWindow", "BE EF 02 06 00 13 CE AA 00 00 00 00 00", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_poweroffcommand.setObjectName(_fromUtf8("projector_poweroffcommand"))
        self.label_21 = QtGui.QLabel(self.projectorsettings)
        self.label_21.setGeometry(QtCore.QRect(10, 120, 121, 16))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Power Off Command:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.projector_applysettings = QtGui.QPushButton(self.projectorsettings)
        self.projector_applysettings.setGeometry(QtCore.QRect(170, 170, 75, 23))
        self.projector_applysettings.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_applysettings.setObjectName(_fromUtf8("projector_applysettings"))
        self.projector_testpoweroffcommand = QtGui.QPushButton(self.projectorsettings)
        self.projector_testpoweroffcommand.setGeometry(QtCore.QRect(50, 170, 91, 23))
        self.projector_testpoweroffcommand.setText(QtGui.QApplication.translate("MainWindow", "Test Power Off", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_testpoweroffcommand.setObjectName(_fromUtf8("projector_testpoweroffcommand"))
        self.projectorcontrol = QtGui.QCheckBox(self.centralwidget)
        self.projectorcontrol.setGeometry(QtCore.QRect(720, 490, 151, 17))
        self.projectorcontrol.setText(QtGui.QApplication.translate("MainWindow", "Enable Projector Control?", None, QtGui.QApplication.UnicodeUTF8))
        self.projectorcontrol.setChecked(True)
        self.projectorcontrol.setObjectName(_fromUtf8("projectorcontrol"))
        self.button_stop_printing = QtGui.QPushButton(self.centralwidget)
        self.button_stop_printing.setEnabled(False)
        self.button_stop_printing.setGeometry(QtCore.QRect(420, 560, 75, 23))
        self.button_stop_printing.setText(QtGui.QApplication.translate("MainWindow", "Stop Printing", None, QtGui.QApplication.UnicodeUTF8))
        self.button_stop_printing.setObjectName(_fromUtf8("button_stop_printing"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFIle = QtGui.QMenu(self.menubar)
        self.menuFIle.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFIle.setObjectName(_fromUtf8("menuFIle"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open Model", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionLoad_Image = QtGui.QAction(MainWindow)
        self.actionLoad_Image.setText(QtGui.QApplication.translate("MainWindow", "Load Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Image.setObjectName(_fromUtf8("actionLoad_Image"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.menuFIle.addAction(self.actionOpen)
        self.menuFIle.addAction(self.actionQuit)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.sliceandprintpressed)
        QtCore.QObject.connect(self.actionOpen, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.selectfile)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.slicepressed)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.printpressed)
        QtCore.QObject.connect(self.toolButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.selectfile)
        QtCore.QObject.connect(self.projectorcontrol, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.projectorcontroltoggle)
        QtCore.QObject.connect(self.button_stop_printing, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.stopthread)
        QtCore.QObject.connect(self.radio_pymcu, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.printercontroltoggle)
        QtCore.QObject.connect(self.enableprintercontrol, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.enableprintercontroltoggled)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.openaboutdialog)
        QtCore.QObject.connect(self.projector_testpoweroffcommand, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.testprojectorpoweroff)
        QtCore.QObject.connect(self.enableslideshow, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.slideshowcontroltoggled)
        QtCore.QObject.connect(self.actionHelp, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.openhelp)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Printing Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Slicing Settings", None, QtGui.QApplication.UnicodeUTF8))

