# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '3dlp.ui'
#
# Created: Sun Nov 18 20:44:16 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1016, 768)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(158, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(158, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(158, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(158, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "3dlp", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/printer3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.ModelFrame = QtGui.QFrame(self.splitter)
        self.ModelFrame.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ModelFrame.sizePolicy().hasHeightForWidth())
        self.ModelFrame.setSizePolicy(sizePolicy)
        self.ModelFrame.setMinimumSize(QtCore.QSize(690, 550))
        self.ModelFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.ModelFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.ModelFrame.setObjectName(_fromUtf8("ModelFrame"))
        self.verticalLayout_25.addWidget(self.splitter)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "Slice and Print", None, QtGui.QApplication.UnicodeUTF8))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/media_play_green.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Slice only ", None, QtGui.QApplication.UnicodeUTF8))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/transform.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "Print only", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.button_stop_printing = QtGui.QPushButton(self.centralwidget)
        self.button_stop_printing.setEnabled(True)
        self.button_stop_printing.setText(QtGui.QApplication.translate("MainWindow", "Stop Printing", None, QtGui.QApplication.UnicodeUTF8))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_stop_printing.setIcon(icon3)
        self.button_stop_printing.setIconSize(QtCore.QSize(24, 24))
        self.button_stop_printing.setObjectName(_fromUtf8("button_stop_printing"))
        self.horizontalLayout.addWidget(self.button_stop_printing)
        self.verticalLayout_25.addLayout(self.horizontalLayout)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(300, 50))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.consoletext = QtGui.QTextEdit(self.groupBox_3)
        self.consoletext.setReadOnly(True)
        self.consoletext.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.consoletext.setObjectName(_fromUtf8("consoletext"))
        self.verticalLayout_2.addWidget(self.consoletext)
        self.verticalLayout_25.addWidget(self.groupBox_3)
        self.horizontalLayout_21.addLayout(self.verticalLayout_25)
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setMinimumSize(QtCore.QSize(200, 375))
        self.toolBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 296, 288))
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.enableprintercontrol = QtGui.QCheckBox(self.page)
        self.enableprintercontrol.setText(QtGui.QApplication.translate("MainWindow", "Enable Printer Control?", None, QtGui.QApplication.UnicodeUTF8))
        self.enableprintercontrol.setChecked(False)
        self.enableprintercontrol.setObjectName(_fromUtf8("enableprintercontrol"))
        self.verticalLayout.addWidget(self.enableprintercontrol)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radio_arduinoUno = QtGui.QRadioButton(self.page)
        self.radio_arduinoUno.setText(QtGui.QApplication.translate("MainWindow", "Arduino Uno", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_arduinoUno.setChecked(True)
        self.radio_arduinoUno.setObjectName(_fromUtf8("radio_arduinoUno"))
        self.horizontalLayout_4.addWidget(self.radio_arduinoUno)
        self.radio_arduinoMega = QtGui.QRadioButton(self.page)
        self.radio_arduinoMega.setText(QtGui.QApplication.translate("MainWindow", "Arduino Mega", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_arduinoMega.setObjectName(_fromUtf8("radio_arduinoMega"))
        self.horizontalLayout_4.addWidget(self.radio_arduinoMega)
        self.radio_pyMCU = QtGui.QRadioButton(self.page)
        self.radio_pyMCU.setText(QtGui.QApplication.translate("MainWindow", "PyMCU", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_pyMCU.setObjectName(_fromUtf8("radio_pyMCU"))
        self.horizontalLayout_4.addWidget(self.radio_pyMCU)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_29 = QtGui.QLabel(self.page)
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_3.addWidget(self.label_29)
        self.pickcom = QtGui.QComboBox(self.page)
        self.pickcom.setObjectName(_fromUtf8("pickcom"))
        self.horizontalLayout_3.addWidget(self.pickcom)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_24 = QtGui.QLabel(self.page)
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Baud:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_3.addWidget(self.label_24)
        self.printerbaud = QtGui.QComboBox(self.page)
        self.printerbaud.setObjectName(_fromUtf8("printerbaud"))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(0, QtGui.QApplication.translate("MainWindow", "115200", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(1, QtGui.QApplication.translate("MainWindow", "57600", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(2, QtGui.QApplication.translate("MainWindow", "38400", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(3, QtGui.QApplication.translate("MainWindow", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(4, QtGui.QApplication.translate("MainWindow", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(5, QtGui.QApplication.translate("MainWindow", "4800", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(6, QtGui.QApplication.translate("MainWindow", "2400", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_3.addWidget(self.printerbaud)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Remote Host Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.remote_port = QtGui.QLineEdit(self.page)
        self.remote_port.setEnabled(False)
        self.remote_port.setText(_fromUtf8(""))
        self.remote_port.setObjectName(_fromUtf8("remote_port"))
        self.horizontalLayout_5.addWidget(self.remote_port)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_6 = QtGui.QLabel(self.page)
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Exposure Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_20.addWidget(self.label_6)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.exposure_time = QtGui.QLineEdit(self.page)
        self.exposure_time.setText(_fromUtf8(""))
        self.exposure_time.setObjectName(_fromUtf8("exposure_time"))
        self.horizontalLayout_6.addWidget(self.exposure_time)
        self.label_28 = QtGui.QLabel(self.page)
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_6.addWidget(self.label_28)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_26 = QtGui.QLabel(self.page)
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Number of starting layers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_8.addWidget(self.label_26)
        self.starting_layers = QtGui.QLineEdit(self.page)
        self.starting_layers.setText(_fromUtf8(""))
        self.starting_layers.setObjectName(_fromUtf8("starting_layers"))
        self.horizontalLayout_8.addWidget(self.starting_layers)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_27 = QtGui.QLabel(self.page)
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Starting layer exposure ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_9.addWidget(self.label_27)
        self.starting_layer_exposure = QtGui.QLineEdit(self.page)
        self.starting_layer_exposure.setText(_fromUtf8(""))
        self.starting_layer_exposure.setObjectName(_fromUtf8("starting_layer_exposure"))
        self.horizontalLayout_9.addWidget(self.starting_layer_exposure)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.enableslideshow = QtGui.QCheckBox(self.page)
        self.enableslideshow.setText(QtGui.QApplication.translate("MainWindow", "Slideshow enabled?", None, QtGui.QApplication.UnicodeUTF8))
        self.enableslideshow.setChecked(False)
        self.enableslideshow.setObjectName(_fromUtf8("enableslideshow"))
        self.verticalLayout.addWidget(self.enableslideshow)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_25 = QtGui.QLabel(self.page)
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Choose monitor to print on:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_10.addWidget(self.label_25)
        self.pickscreen = QtGui.QComboBox(self.page)
        self.pickscreen.setObjectName(_fromUtf8("pickscreen"))
        self.horizontalLayout_10.addWidget(self.pickscreen)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 296, 288))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_7 = QtGui.QLabel(self.page_2)
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Image Height", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_8.addWidget(self.label_7)
        self.image_height = QtGui.QLineEdit(self.page_2)
        self.image_height.setText(_fromUtf8(""))
        self.image_height.setObjectName(_fromUtf8("image_height"))
        self.verticalLayout_8.addWidget(self.image_height)
        self.horizontalLayout_12.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_8 = QtGui.QLabel(self.page_2)
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Image Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_9.addWidget(self.label_8)
        self.image_width = QtGui.QLineEdit(self.page_2)
        self.image_width.setText(_fromUtf8(""))
        self.image_width.setObjectName(_fromUtf8("image_width"))
        self.verticalLayout_9.addWidget(self.image_width)
        self.horizontalLayout_12.addLayout(self.verticalLayout_9)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_9 = QtGui.QLabel(self.page_2)
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Layer Thickness", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_10.addWidget(self.label_9)
        self.layer_thickness = QtGui.QLineEdit(self.page_2)
        self.layer_thickness.setText(_fromUtf8(""))
        self.layer_thickness.setObjectName(_fromUtf8("layer_thickness"))
        self.verticalLayout_10.addWidget(self.layer_thickness)
        self.horizontalLayout_13.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_10 = QtGui.QLabel(self.page_2)
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Slicing Plane", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_11.addWidget(self.label_10)
        self.slicing_plane = QtGui.QComboBox(self.page_2)
        self.slicing_plane.setObjectName(_fromUtf8("slicing_plane"))
        self.slicing_plane.addItem(_fromUtf8(""))
        self.slicing_plane.setItemText(0, QtGui.QApplication.translate("MainWindow", "XZ", None, QtGui.QApplication.UnicodeUTF8))
        self.slicing_plane.addItem(_fromUtf8(""))
        self.slicing_plane.setItemText(1, QtGui.QApplication.translate("MainWindow", "XY", None, QtGui.QApplication.UnicodeUTF8))
        self.slicing_plane.addItem(_fromUtf8(""))
        self.slicing_plane.setItemText(2, QtGui.QApplication.translate("MainWindow", "YZ", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_11.addWidget(self.slicing_plane)
        self.horizontalLayout_13.addLayout(self.verticalLayout_11)
        self.verticalLayout_13.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_13 = QtGui.QLabel(self.page_2)
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Starting Depth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_14.addWidget(self.label_13)
        self.z_options_start = QtGui.QLineEdit(self.page_2)
        self.z_options_start.setText(_fromUtf8(""))
        self.z_options_start.setObjectName(_fromUtf8("z_options_start"))
        self.horizontalLayout_14.addWidget(self.z_options_start)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_22 = QtGui.QLabel(self.page_2)
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Ending Depth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_15.addWidget(self.label_22)
        self.z_options_end = QtGui.QLineEdit(self.page_2)
        self.z_options_end.setText(_fromUtf8(""))
        self.z_options_end.setObjectName(_fromUtf8("z_options_end"))
        self.horizontalLayout_15.addWidget(self.z_options_end)
        self.verticalLayout_13.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_23 = QtGui.QLabel(self.page_2)
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Z slicing increment:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_16.addWidget(self.label_23)
        self.z_options_increment = QtGui.QLineEdit(self.page_2)
        self.z_options_increment.setText(_fromUtf8(""))
        self.z_options_increment.setObjectName(_fromUtf8("z_options_increment"))
        self.horizontalLayout_16.addWidget(self.z_options_increment)
        self.verticalLayout_13.addLayout(self.horizontalLayout_16)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label = QtGui.QLabel(self.page_2)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "File to Slice:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_12.addWidget(self.label)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.displayfilenamelabel = QtGui.QLineEdit(self.page_2)
        self.displayfilenamelabel.setText(_fromUtf8(""))
        self.displayfilenamelabel.setReadOnly(False)
        self.displayfilenamelabel.setObjectName(_fromUtf8("displayfilenamelabel"))
        self.horizontalLayout_17.addWidget(self.displayfilenamelabel)
        self.toolButton = QtGui.QToolButton(self.page_2)
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_17.addWidget(self.toolButton)
        self.verticalLayout_12.addLayout(self.horizontalLayout_17)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_21.addLayout(self.verticalLayout_13)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 296, 288))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.projectorcontrol = QtGui.QCheckBox(self.page_3)
        self.projectorcontrol.setText(QtGui.QApplication.translate("MainWindow", "Enable Projector Control?", None, QtGui.QApplication.UnicodeUTF8))
        self.projectorcontrol.setChecked(False)
        self.projectorcontrol.setObjectName(_fromUtf8("projectorcontrol"))
        self.verticalLayout_19.addWidget(self.projectorcontrol)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_16 = QtGui.QLabel(self.page_3)
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "COM Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_3.addWidget(self.label_16)
        self.projector_pickcom = QtGui.QComboBox(self.page_3)
        self.projector_pickcom.setObjectName(_fromUtf8("projector_pickcom"))
        self.verticalLayout_3.addWidget(self.projector_pickcom)
        self.horizontalLayout_11.addLayout(self.verticalLayout_3)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_17 = QtGui.QLabel(self.page_3)
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Serial Baud rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_14.addWidget(self.label_17)
        self.projector_baud = QtGui.QComboBox(self.page_3)
        self.projector_baud.setObjectName(_fromUtf8("projector_baud"))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(0, QtGui.QApplication.translate("MainWindow", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(1, QtGui.QApplication.translate("MainWindow", "115200", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(2, QtGui.QApplication.translate("MainWindow", "57600", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(3, QtGui.QApplication.translate("MainWindow", "38400", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(4, QtGui.QApplication.translate("MainWindow", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(5, QtGui.QApplication.translate("MainWindow", "4800", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(6, QtGui.QApplication.translate("MainWindow", "2400", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_14.addWidget(self.projector_baud)
        self.horizontalLayout_11.addLayout(self.verticalLayout_14)
        self.verticalLayout_19.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_18 = QtGui.QLabel(self.page_3)
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Parity:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_15.addWidget(self.label_18)
        self.projector_parity = QtGui.QComboBox(self.page_3)
        self.projector_parity.setObjectName(_fromUtf8("projector_parity"))
        self.projector_parity.addItem(_fromUtf8(""))
        self.projector_parity.setItemText(0, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_parity.addItem(_fromUtf8(""))
        self.projector_parity.setItemText(1, QtGui.QApplication.translate("MainWindow", "Even", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_parity.addItem(_fromUtf8(""))
        self.projector_parity.setItemText(2, QtGui.QApplication.translate("MainWindow", "Odd", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_parity.addItem(_fromUtf8(""))
        self.projector_parity.setItemText(3, QtGui.QApplication.translate("MainWindow", "Mark", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_parity.addItem(_fromUtf8(""))
        self.projector_parity.setItemText(4, QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_15.addWidget(self.projector_parity)
        self.horizontalLayout_18.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_19 = QtGui.QLabel(self.page_3)
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Data Bits:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_16.addWidget(self.label_19)
        self.projector_databits = QtGui.QComboBox(self.page_3)
        self.projector_databits.setObjectName(_fromUtf8("projector_databits"))
        self.projector_databits.addItem(_fromUtf8(""))
        self.projector_databits.setItemText(0, QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_databits.addItem(_fromUtf8(""))
        self.projector_databits.setItemText(1, QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_databits.addItem(_fromUtf8(""))
        self.projector_databits.setItemText(2, QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_databits.addItem(_fromUtf8(""))
        self.projector_databits.setItemText(3, QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_16.addWidget(self.projector_databits)
        self.horizontalLayout_18.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_20 = QtGui.QLabel(self.page_3)
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Stop Bits:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_17.addWidget(self.label_20)
        self.projector_stopbits = QtGui.QComboBox(self.page_3)
        self.projector_stopbits.setObjectName(_fromUtf8("projector_stopbits"))
        self.projector_stopbits.addItem(_fromUtf8(""))
        self.projector_stopbits.setItemText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_stopbits.addItem(_fromUtf8(""))
        self.projector_stopbits.setItemText(1, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_17.addWidget(self.projector_stopbits)
        self.horizontalLayout_18.addLayout(self.verticalLayout_17)
        self.verticalLayout_19.addLayout(self.horizontalLayout_18)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_21 = QtGui.QLabel(self.page_3)
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Power Off Command:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_18.addWidget(self.label_21)
        self.projector_poweroffcommand = QtGui.QLineEdit(self.page_3)
        self.projector_poweroffcommand.setText(_fromUtf8(""))
        self.projector_poweroffcommand.setObjectName(_fromUtf8("projector_poweroffcommand"))
        self.verticalLayout_18.addWidget(self.projector_poweroffcommand)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.projector_testpoweroffcommand = QtGui.QPushButton(self.page_3)
        self.projector_testpoweroffcommand.setText(QtGui.QApplication.translate("MainWindow", "Test Power Off", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_testpoweroffcommand.setObjectName(_fromUtf8("projector_testpoweroffcommand"))
        self.horizontalLayout_2.addWidget(self.projector_testpoweroffcommand)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_19.addLayout(self.horizontalLayout_2)
        self.verticalLayout_22.addLayout(self.verticalLayout_19)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.verticalLayout_24.addWidget(self.toolBox)
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setMinimumSize(QtCore.QSize(200, 50))
        self.groupBox_6.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Custom Z-axis command", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.zscript = QtGui.QPlainTextEdit(self.groupBox_6)
        self.zscript.setPlainText(_fromUtf8(""))
        self.zscript.setObjectName(_fromUtf8("zscript"))
        self.verticalLayout_5.addWidget(self.zscript)
        self.verticalLayout_24.addWidget(self.groupBox_6)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setSpacing(6)
        self.verticalLayout_23.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Slice Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_23.addWidget(self.label_2)
        self.SliceFrame = QtGui.QFrame(self.centralwidget)
        self.SliceFrame.setMinimumSize(QtCore.QSize(275, 200))
        self.SliceFrame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.SliceFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.SliceFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.SliceFrame.setObjectName(_fromUtf8("SliceFrame"))
        self.verticalLayout_23.addWidget(self.SliceFrame)
        self.verticalLayout_24.addLayout(self.verticalLayout_23)
        self.horizontalLayout_21.addLayout(self.verticalLayout_24)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_21)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1016, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.toolBar.setPalette(palette)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Main Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setAutoFillBackground(True)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.toolBar_2.setPalette(palette)
        self.toolBar_2.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_2.setAutoFillBackground(True)
        self.toolBar_2.setMovable(False)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionQuit = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/delete2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon4)
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionOpen = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/import1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon5)
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open Model", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionLoad_Image = QtGui.QAction(MainWindow)
        self.actionLoad_Image.setText(QtGui.QApplication.translate("MainWindow", "Load Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Image.setObjectName(_fromUtf8("actionLoad_Image"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon6)
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionHelp = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/question_and_answer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon7)
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionSave_current_settings_as_default = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/notebook_preferences.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_current_settings_as_default.setIcon(icon8)
        self.actionSave_current_settings_as_default.setText(QtGui.QApplication.translate("MainWindow", "Save current settings as default", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_current_settings_as_default.setObjectName(_fromUtf8("actionSave_current_settings_as_default"))
        self.actionOpen_manual_printer_control = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/lightbulb_on.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_manual_printer_control.setIcon(icon9)
        self.actionOpen_manual_printer_control.setText(QtGui.QApplication.translate("MainWindow", "Open manual printer control", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_manual_printer_control.setObjectName(_fromUtf8("actionOpen_manual_printer_control"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/gear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon10)
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setToolTip(QtGui.QApplication.translate("MainWindow", "Manage Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionNext_Slice = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/media_step_forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext_Slice.setIcon(icon11)
        self.actionNext_Slice.setText(QtGui.QApplication.translate("MainWindow", "Next Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Slice.setToolTip(QtGui.QApplication.translate("MainWindow", "Preview Next Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Slice.setObjectName(_fromUtf8("actionNext_Slice"))
        self.actionPrevious_Slice = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/media_step_back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrevious_Slice.setIcon(icon12)
        self.actionPrevious_Slice.setText(QtGui.QApplication.translate("MainWindow", "Previous Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_Slice.setToolTip(QtGui.QApplication.translate("MainWindow", "Preview Previous Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_Slice.setObjectName(_fromUtf8("actionPrevious_Slice"))
        self.actionFirst_Slice = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/media_beginning.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFirst_Slice.setIcon(icon13)
        self.actionFirst_Slice.setText(QtGui.QApplication.translate("MainWindow", "First Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirst_Slice.setToolTip(QtGui.QApplication.translate("MainWindow", "Preview First Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirst_Slice.setObjectName(_fromUtf8("actionFirst_Slice"))
        self.actionLast_Slice = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/media_end.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLast_Slice.setIcon(icon14)
        self.actionLast_Slice.setText(QtGui.QApplication.translate("MainWindow", "Last Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLast_Slice.setToolTip(QtGui.QApplication.translate("MainWindow", "Preview Last Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLast_Slice.setObjectName(_fromUtf8("actionLast_Slice"))
        self.actionSet_Model_Opacity = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/replace.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSet_Model_Opacity.setIcon(icon15)
        self.actionSet_Model_Opacity.setText(QtGui.QApplication.translate("MainWindow", "Set Model Opacity", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Model_Opacity.setToolTip(QtGui.QApplication.translate("MainWindow", "Set Model Opacity in 3D View Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Model_Opacity.setObjectName(_fromUtf8("actionSet_Model_Opacity"))
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionHelp)
        self.menuTools.addAction(self.actionOpen_manual_printer_control)
        self.menuTools.addAction(self.actionSave_current_settings_as_default)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionOpen_manual_printer_control)
        self.toolBar.addAction(self.actionSet_Model_Opacity)
        self.toolBar.addAction(self.actionPreferences)
        self.toolBar_2.addAction(self.actionFirst_Slice)
        self.toolBar_2.addAction(self.actionPrevious_Slice)
        self.toolBar_2.addAction(self.actionNext_Slice)
        self.toolBar_2.addAction(self.actionLast_Slice)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.sliceandprintpressed)
        QtCore.QObject.connect(self.actionOpen, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.selectfile)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.slicepressed)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.printpressed)
        QtCore.QObject.connect(self.toolButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.selectfile)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.openaboutdialog)
        QtCore.QObject.connect(self.actionHelp, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.openhelp)
        QtCore.QObject.connect(self.enableprintercontrol, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.EnablePrinterControlToggled)
        QtCore.QObject.connect(self.enableslideshow, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.SlideshowControlToggled)
        QtCore.QObject.connect(self.projectorcontrol, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.ProjectorControlToggled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("MainWindow", "Printing Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("MainWindow", "Slicing Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QtGui.QApplication.translate("MainWindow", "Projector Settings", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc
