# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '3dlp_v2.ui'
#
# Created: Sun Jun 23 20:31:53 2013
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1281, 835)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "3dlp", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/3d printing.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(_fromUtf8("#MainWindow {background-image: url(:/backgrounds/backgrounds/generic_abstract_wallpaper_4_by_zoken-d3087ac.png);}"))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setStyleSheet(_fromUtf8(""))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setMargin(0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.workspacePre = QtGui.QWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workspacePre.sizePolicy().hasHeightForWidth())
        self.workspacePre.setSizePolicy(sizePolicy)
        self.workspacePre.setObjectName(_fromUtf8("workspacePre"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.workspacePre)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setMargin(0)
        self.horizontalLayout_19.setMargin(0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.modelFramePre = QtGui.QFrame(self.workspacePre)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelFramePre.sizePolicy().hasHeightForWidth())
        self.modelFramePre.setSizePolicy(sizePolicy)
        self.modelFramePre.setFrameShape(QtGui.QFrame.Box)
        self.modelFramePre.setFrameShadow(QtGui.QFrame.Raised)
        self.modelFramePre.setObjectName(_fromUtf8("modelFramePre"))
        self.horizontalLayout_19.addWidget(self.modelFramePre)
        self.horizontalLayout_20.addWidget(self.workspacePre)
        self.workspacePost = QtGui.QWidget(self.frame)
        self.workspacePost.setObjectName(_fromUtf8("workspacePost"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.workspacePost)
        self.horizontalLayout_18.setMargin(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.modelFramePost = QtGui.QFrame(self.workspacePost)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelFramePost.sizePolicy().hasHeightForWidth())
        self.modelFramePost.setSizePolicy(sizePolicy)
        self.modelFramePost.setFrameShape(QtGui.QFrame.Box)
        self.modelFramePost.setFrameShadow(QtGui.QFrame.Raised)
        self.modelFramePost.setObjectName(_fromUtf8("modelFramePost"))
        self.horizontalLayout_17.addWidget(self.modelFramePost)
        self.sliceFramePost = QtGui.QFrame(self.workspacePost)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceFramePost.sizePolicy().hasHeightForWidth())
        self.sliceFramePost.setSizePolicy(sizePolicy)
        self.sliceFramePost.setFrameShape(QtGui.QFrame.Box)
        self.sliceFramePost.setFrameShadow(QtGui.QFrame.Raised)
        self.sliceFramePost.setObjectName(_fromUtf8("sliceFramePost"))
        self.horizontalLayout_17.addWidget(self.sliceFramePost)
        self.verticalLayout_13.addLayout(self.horizontalLayout_17)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem)
        self.toolButton_4 = QtGui.QToolButton(self.workspacePost)
        self.toolButton_4.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/media_beginning.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon1)
        self.toolButton_4.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.horizontalLayout_25.addWidget(self.toolButton_4)
        self.toolButton_3 = QtGui.QToolButton(self.workspacePost)
        self.toolButton_3.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/media_step_back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon2)
        self.toolButton_3.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.horizontalLayout_25.addWidget(self.toolButton_3)
        self.toolButton = QtGui.QToolButton(self.workspacePost)
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/media_step_forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon3)
        self.toolButton.setIconSize(QtCore.QSize(24, 24))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_25.addWidget(self.toolButton)
        self.toolButton_6 = QtGui.QToolButton(self.workspacePost)
        self.toolButton_6.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/media_end.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon4)
        self.toolButton_6.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_6.setObjectName(_fromUtf8("toolButton_6"))
        self.horizontalLayout_25.addWidget(self.toolButton_6)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_25)
        self.verticalLayout_13.addLayout(self.verticalLayout_10)
        self.horizontalLayout_18.addLayout(self.verticalLayout_13)
        self.horizontalLayout_20.addWidget(self.workspacePost)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_22.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1281, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuWindow_2 = QtGui.QMenu(self.menubar)
        self.menuWindow_2.setTitle(QtGui.QApplication.translate("MainWindow", "Window", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindow_2.setObjectName(_fromUtf8("menuWindow_2"))
        self.menuShow_Workspace = QtGui.QMenu(self.menuWindow_2)
        self.menuShow_Workspace.setTitle(QtGui.QApplication.translate("MainWindow", "Show Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.menuShow_Workspace.setObjectName(_fromUtf8("menuShow_Workspace"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.toolBar.setPalette(palette)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Main Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setAutoFillBackground(True)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_3 = QtGui.QToolBar(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.toolBar_3.setPalette(palette)
        self.toolBar_3.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_3", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_3.setAutoFillBackground(True)
        self.toolBar_3.setMovable(False)
        self.toolBar_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar_3.setFloatable(True)
        self.toolBar_3.setObjectName(_fromUtf8("toolBar_3"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_3)
        self.toolbar = QtGui.QDockWidget(MainWindow)
        self.toolbar.setAutoFillBackground(False)
        self.toolbar.setFloating(False)
        self.toolbar.setFeatures(QtGui.QDockWidget.NoDockWidgetFeatures)
        self.toolbar.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.toolbar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbar.setObjectName(_fromUtf8("toolbar"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.toolbarFrame = QtGui.QFrame(self.dockWidgetContents)
        self.toolbarFrame.setAutoFillBackground(True)
        self.toolbarFrame.setFrameShape(QtGui.QFrame.Box)
        self.toolbarFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.toolbarFrame.setObjectName(_fromUtf8("toolbarFrame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.toolbarFrame)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.toolButton_9 = QtGui.QToolButton(self.toolbarFrame)
        self.toolButton_9.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Clone.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_9.setIcon(icon5)
        self.toolButton_9.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_9.setObjectName(_fromUtf8("toolButton_9"))
        self.verticalLayout_3.addWidget(self.toolButton_9)
        self.toolButton_8 = QtGui.QToolButton(self.toolbarFrame)
        self.toolButton_8.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Color palette.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_8.setIcon(icon6)
        self.toolButton_8.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_8.setObjectName(_fromUtf8("toolButton_8"))
        self.verticalLayout_3.addWidget(self.toolButton_8)
        self.toolButton_7 = QtGui.QToolButton(self.toolbarFrame)
        self.toolButton_7.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/3d rotation.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_7.setIcon(icon7)
        self.toolButton_7.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_7.setObjectName(_fromUtf8("toolButton_7"))
        self.verticalLayout_3.addWidget(self.toolButton_7)
        self.toolButton_5 = QtGui.QToolButton(self.toolbarFrame)
        self.toolButton_5.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Clipping.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon8)
        self.toolButton_5.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_5.setObjectName(_fromUtf8("toolButton_5"))
        self.verticalLayout_3.addWidget(self.toolButton_5)
        self.toolButton_2 = QtGui.QToolButton(self.toolbarFrame)
        self.toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Frame cube.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon9)
        self.toolButton_2.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.verticalLayout_3.addWidget(self.toolButton_2)
        self.toolButton_17 = QtGui.QToolButton(self.toolbarFrame)
        self.toolButton_17.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Predefined views.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_17.setIcon(icon10)
        self.toolButton_17.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_17.setObjectName(_fromUtf8("toolButton_17"))
        self.verticalLayout_3.addWidget(self.toolButton_17)
        self.toolButton_19 = QtGui.QToolButton(self.toolbarFrame)
        self.toolButton_19.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Ungroup.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_19.setIcon(icon11)
        self.toolButton_19.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_19.setObjectName(_fromUtf8("toolButton_19"))
        self.verticalLayout_3.addWidget(self.toolButton_19)
        self.toolButton_20 = QtGui.QToolButton(self.toolbarFrame)
        self.toolButton_20.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Group.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_20.setIcon(icon12)
        self.toolButton_20.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_20.setObjectName(_fromUtf8("toolButton_20"))
        self.verticalLayout_3.addWidget(self.toolButton_20)
        self.toolButton_13 = QtGui.QToolButton(self.toolbarFrame)
        self.toolButton_13.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Object tree.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_13.setIcon(icon13)
        self.toolButton_13.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_13.setObjectName(_fromUtf8("toolButton_13"))
        self.verticalLayout_3.addWidget(self.toolButton_13)
        self.toolButton_34 = QtGui.QToolButton(self.toolbarFrame)
        self.toolButton_34.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Edit.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_34.setIcon(icon14)
        self.toolButton_34.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_34.setObjectName(_fromUtf8("toolButton_34"))
        self.verticalLayout_3.addWidget(self.toolButton_34)
        self.toolButton_25 = QtGui.QToolButton(self.toolbarFrame)
        self.toolButton_25.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Scale.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_25.setIcon(icon15)
        self.toolButton_25.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_25.setObjectName(_fromUtf8("toolButton_25"))
        self.verticalLayout_3.addWidget(self.toolButton_25)
        self.toolButton_11 = QtGui.QToolButton(self.toolbarFrame)
        self.toolButton_11.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Cube.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_11.setIcon(icon16)
        self.toolButton_11.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_11.setObjectName(_fromUtf8("toolButton_11"))
        self.verticalLayout_3.addWidget(self.toolButton_11)
        self.toolButton_27 = QtGui.QToolButton(self.toolbarFrame)
        self.toolButton_27.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Units.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_27.setIcon(icon17)
        self.toolButton_27.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_27.setObjectName(_fromUtf8("toolButton_27"))
        self.verticalLayout_3.addWidget(self.toolButton_27)
        self.toolButton_21 = QtGui.QToolButton(self.toolbarFrame)
        self.toolButton_21.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Size.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_21.setIcon(icon18)
        self.toolButton_21.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_21.setObjectName(_fromUtf8("toolButton_21"))
        self.verticalLayout_3.addWidget(self.toolButton_21)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addWidget(self.toolbarFrame)
        spacerItem2 = QtGui.QSpacerItem(20, 97, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.toolbar.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.toolbar)
        self.logBar = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logBar.sizePolicy().hasHeightForWidth())
        self.logBar.setSizePolicy(sizePolicy)
        self.logBar.setMinimumSize(QtCore.QSize(89, 115))
        self.logBar.setAutoFillBackground(False)
        self.logBar.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.logBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Log Console", None, QtGui.QApplication.UnicodeUTF8))
        self.logBar.setObjectName(_fromUtf8("logBar"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.consoletext = QtGui.QTextEdit(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consoletext.sizePolicy().hasHeightForWidth())
        self.consoletext.setSizePolicy(sizePolicy)
        self.consoletext.setMaximumSize(QtCore.QSize(16777215, 75))
        self.consoletext.setBaseSize(QtCore.QSize(0, 75))
        self.consoletext.setReadOnly(True)
        self.consoletext.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.consoletext.setObjectName(_fromUtf8("consoletext"))
        self.verticalLayout_2.addWidget(self.consoletext)
        self.logBar.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.logBar)
        self.sliceListBar = QtGui.QDockWidget(MainWindow)
        self.sliceListBar.setMinimumSize(QtCore.QSize(228, 148))
        self.sliceListBar.setObjectName(_fromUtf8("sliceListBar"))
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName(_fromUtf8("dockWidgetContents_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.dockWidgetContents_6)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents_6)
        self.tabWidget.setStyleSheet(_fromUtf8("selection-background-color: rgb(239, 239, 239);"))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "No slices to show!", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton_5 = QtGui.QPushButton(self.dockWidgetContents_6)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "Print", None, QtGui.QApplication.UnicodeUTF8))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/printer icons/icons/printer/Start 3d-printing.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon19)
        self.pushButton_5.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.sliceListBar.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.sliceListBar)
        self.printJobInfoBar = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.printJobInfoBar.sizePolicy().hasHeightForWidth())
        self.printJobInfoBar.setSizePolicy(sizePolicy)
        self.printJobInfoBar.setMaximumSize(QtCore.QSize(524287, 120))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.printJobInfoBar.setPalette(palette)
        self.printJobInfoBar.setAutoFillBackground(False)
        self.printJobInfoBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Print Job Information", None, QtGui.QApplication.UnicodeUTF8))
        self.printJobInfoBar.setObjectName(_fromUtf8("printJobInfoBar"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.dockWidgetContents_3)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.frame_4 = QtGui.QFrame(self.dockWidgetContents_3)
        self.frame_4.setAutoFillBackground(True)
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", " Time to print: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "0:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", " Volume of resin needed to print: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.label_7 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.label_6 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", " cm^3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", " Total cost to print: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.label_8 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "$ ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.horizontalLayout_7.addWidget(self.frame_4)
        self.printJobInfoBar.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.printJobInfoBar)
        self.preSliceBar = QtGui.QDockWidget(MainWindow)
        self.preSliceBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Model Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.preSliceBar.setObjectName(_fromUtf8("preSliceBar"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.dockWidgetContents_4)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setMargin(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.frame_2 = QtGui.QFrame(self.dockWidgetContents_4)
        self.frame_2.setAutoFillBackground(True)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.toolButton_10 = QtGui.QToolButton(self.frame_2)
        self.toolButton_10.setText(QtGui.QApplication.translate("MainWindow", "Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_10.setIcon(icon8)
        self.toolButton_10.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_10.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_10.setObjectName(_fromUtf8("toolButton_10"))
        self.verticalLayout_9.addWidget(self.toolButton_10)
        self.groupBox_2 = QtGui.QGroupBox(self.frame_2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_2.setMaximumSize(QtCore.QSize(254, 16777215))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Model List", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.addModel = QtGui.QPushButton(self.groupBox_2)
        self.addModel.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.addModel.setObjectName(_fromUtf8("addModel"))
        self.horizontalLayout_10.addWidget(self.addModel)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.removeModel = QtGui.QPushButton(self.groupBox_2)
        self.removeModel.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.removeModel.setObjectName(_fromUtf8("removeModel"))
        self.horizontalLayout_10.addWidget(self.removeModel)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.modelList = QtGui.QListWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelList.sizePolicy().hasHeightForWidth())
        self.modelList.setSizePolicy(sizePolicy)
        self.modelList.setFrameShadow(QtGui.QFrame.Plain)
        self.modelList.setAlternatingRowColors(False)
        self.modelList.setSpacing(1)
        self.modelList.setModelColumn(0)
        self.modelList.setObjectName(_fromUtf8("modelList"))
        self.verticalLayout_7.addWidget(self.modelList)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.Transform_groupbox = QtGui.QGroupBox(self.frame_2)
        self.Transform_groupbox.setEnabled(False)
        self.Transform_groupbox.setMaximumSize(QtCore.QSize(254, 16777215))
        self.Transform_groupbox.setTitle(QtGui.QApplication.translate("MainWindow", "Transform Model", None, QtGui.QApplication.UnicodeUTF8))
        self.Transform_groupbox.setObjectName(_fromUtf8("Transform_groupbox"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.Transform_groupbox)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_12 = QtGui.QLabel(self.Transform_groupbox)
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_8.addWidget(self.label_12)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_10 = QtGui.QLabel(self.Transform_groupbox)
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_12.addWidget(self.label_10)
        self.positionX = QtGui.QDoubleSpinBox(self.Transform_groupbox)
        self.positionX.setMinimumSize(QtCore.QSize(55, 0))
        self.positionX.setMinimum(-99.99)
        self.positionX.setObjectName(_fromUtf8("positionX"))
        self.horizontalLayout_12.addWidget(self.positionX)
        self.label_11 = QtGui.QLabel(self.Transform_groupbox)
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_12.addWidget(self.label_11)
        self.positionY = QtGui.QDoubleSpinBox(self.Transform_groupbox)
        self.positionY.setMinimumSize(QtCore.QSize(55, 0))
        self.positionY.setMinimum(-99.99)
        self.positionY.setObjectName(_fromUtf8("positionY"))
        self.horizontalLayout_12.addWidget(self.positionY)
        self.label_13 = QtGui.QLabel(self.Transform_groupbox)
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_12.addWidget(self.label_13)
        self.positionZ = QtGui.QDoubleSpinBox(self.Transform_groupbox)
        self.positionZ.setMinimumSize(QtCore.QSize(55, 0))
        self.positionZ.setMinimum(-99.99)
        self.positionZ.setObjectName(_fromUtf8("positionZ"))
        self.horizontalLayout_12.addWidget(self.positionZ)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.label_14 = QtGui.QLabel(self.Transform_groupbox)
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Rotation:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_8.addWidget(self.label_14)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_15 = QtGui.QLabel(self.Transform_groupbox)
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_13.addWidget(self.label_15)
        self.rotationX = QtGui.QDoubleSpinBox(self.Transform_groupbox)
        self.rotationX.setMinimumSize(QtCore.QSize(55, 0))
        self.rotationX.setDecimals(0)
        self.rotationX.setMinimum(-360.0)
        self.rotationX.setMaximum(360.0)
        self.rotationX.setObjectName(_fromUtf8("rotationX"))
        self.horizontalLayout_13.addWidget(self.rotationX)
        self.label_16 = QtGui.QLabel(self.Transform_groupbox)
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_13.addWidget(self.label_16)
        self.rotationY = QtGui.QDoubleSpinBox(self.Transform_groupbox)
        self.rotationY.setMinimumSize(QtCore.QSize(55, 0))
        self.rotationY.setDecimals(0)
        self.rotationY.setMinimum(-360.0)
        self.rotationY.setMaximum(360.0)
        self.rotationY.setObjectName(_fromUtf8("rotationY"))
        self.horizontalLayout_13.addWidget(self.rotationY)
        self.label_17 = QtGui.QLabel(self.Transform_groupbox)
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_13.addWidget(self.label_17)
        self.rotationZ = QtGui.QDoubleSpinBox(self.Transform_groupbox)
        self.rotationZ.setMinimumSize(QtCore.QSize(55, 0))
        self.rotationZ.setDecimals(0)
        self.rotationZ.setMinimum(-360.0)
        self.rotationZ.setMaximum(360.0)
        self.rotationZ.setObjectName(_fromUtf8("rotationZ"))
        self.horizontalLayout_13.addWidget(self.rotationZ)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_18 = QtGui.QLabel(self.Transform_groupbox)
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Scaling Factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_14.addWidget(self.label_18)
        self.scale = QtGui.QDoubleSpinBox(self.Transform_groupbox)
        self.scale.setMinimumSize(QtCore.QSize(55, 0))
        self.scale.setDecimals(0)
        self.scale.setMinimum(0.0)
        self.scale.setMaximum(500.0)
        self.scale.setSingleStep(1.0)
        self.scale.setProperty("value", 100.0)
        self.scale.setObjectName(_fromUtf8("scale"))
        self.horizontalLayout_14.addWidget(self.scale)
        self.label_19 = QtGui.QLabel(self.Transform_groupbox)
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_14.addWidget(self.label_19)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_11.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addWidget(self.Transform_groupbox)
        self.groupBox = QtGui.QGroupBox(self.frame_2)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox.setMaximumSize(QtCore.QSize(254, 16777215))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Model Information", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.verticalLayout_11.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_22 = QtGui.QLabel(self.groupBox)
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Model Volume:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_24.addWidget(self.label_22)
        self.label_23 = QtGui.QLabel(self.groupBox)
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "cm^3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_24.addWidget(self.label_23)
        self.verticalLayout_11.addLayout(self.horizontalLayout_24)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem8)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.horizontalLayout_15.addLayout(self.verticalLayout_9)
        self.horizontalLayout_16.addWidget(self.frame_2)
        self.preSliceBar.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.preSliceBar)
        self.actionQuit = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Close.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon20)
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionOpen = QtGui.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Open.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon21)
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open Existing Print Job", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon22)
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionHelp = QtGui.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/question_and_answer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon23)
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionSave_current_settings_as_default = QtGui.QAction(MainWindow)
        self.actionSave_current_settings_as_default.setCheckable(True)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/notebook_preferences.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_current_settings_as_default.setIcon(icon24)
        self.actionSave_current_settings_as_default.setText(QtGui.QApplication.translate("MainWindow", "Save current settings as default", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_current_settings_as_default.setObjectName(_fromUtf8("actionSave_current_settings_as_default"))
        self.actionOpen_manual_printer_control = QtGui.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Hammer.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_manual_printer_control.setIcon(icon25)
        self.actionOpen_manual_printer_control.setText(QtGui.QApplication.translate("MainWindow", "Open Manual Printer Control", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_manual_printer_control.setObjectName(_fromUtf8("actionOpen_manual_printer_control"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Settings.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon26)
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setToolTip(QtGui.QApplication.translate("MainWindow", "Manage Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionNext_Slice = QtGui.QAction(MainWindow)
        self.actionNext_Slice.setIcon(icon3)
        self.actionNext_Slice.setText(QtGui.QApplication.translate("MainWindow", "Next Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Slice.setToolTip(QtGui.QApplication.translate("MainWindow", "Preview Next Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Slice.setObjectName(_fromUtf8("actionNext_Slice"))
        self.actionPrevious_Slice = QtGui.QAction(MainWindow)
        self.actionPrevious_Slice.setIcon(icon2)
        self.actionPrevious_Slice.setText(QtGui.QApplication.translate("MainWindow", "Previous Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_Slice.setToolTip(QtGui.QApplication.translate("MainWindow", "Preview Previous Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_Slice.setObjectName(_fromUtf8("actionPrevious_Slice"))
        self.actionFirst_Slice = QtGui.QAction(MainWindow)
        self.actionFirst_Slice.setIcon(icon1)
        self.actionFirst_Slice.setText(QtGui.QApplication.translate("MainWindow", "First Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirst_Slice.setToolTip(QtGui.QApplication.translate("MainWindow", "Preview First Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirst_Slice.setObjectName(_fromUtf8("actionFirst_Slice"))
        self.actionLast_Slice = QtGui.QAction(MainWindow)
        self.actionLast_Slice.setIcon(icon4)
        self.actionLast_Slice.setText(QtGui.QApplication.translate("MainWindow", "Last Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLast_Slice.setToolTip(QtGui.QApplication.translate("MainWindow", "Preview Last Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLast_Slice.setObjectName(_fromUtf8("actionLast_Slice"))
        self.actionSet_Model_Opacity = QtGui.QAction(MainWindow)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/replace.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSet_Model_Opacity.setIcon(icon27)
        self.actionSet_Model_Opacity.setText(QtGui.QApplication.translate("MainWindow", "Set Model Opacity", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Model_Opacity.setToolTip(QtGui.QApplication.translate("MainWindow", "Set Model Opacity", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Model_Opacity.setObjectName(_fromUtf8("actionSet_Model_Opacity"))
        self.actionGo_To_Layer = QtGui.QAction(MainWindow)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Search.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGo_To_Layer.setIcon(icon28)
        self.actionGo_To_Layer.setText(QtGui.QApplication.translate("MainWindow", "Go To Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGo_To_Layer.setObjectName(_fromUtf8("actionGo_To_Layer"))
        self.actionFirmware_Configurator = QtGui.QAction(MainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Configuration.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFirmware_Configurator.setIcon(icon29)
        self.actionFirmware_Configurator.setText(QtGui.QApplication.translate("MainWindow", "Firmware Configurator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirmware_Configurator.setObjectName(_fromUtf8("actionFirmware_Configurator"))
        self.actionConnect_To_Printer_2 = QtGui.QAction(MainWindow)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Start 3d-printing.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect_To_Printer_2.setIcon(icon30)
        self.actionConnect_To_Printer_2.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect_To_Printer_2.setToolTip(QtGui.QApplication.translate("MainWindow", "Connect to Printer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect_To_Printer_2.setObjectName(_fromUtf8("actionConnect_To_Printer_2"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Save.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon31)
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionNew = QtGui.QAction(MainWindow)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Project.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon32)
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New Print Job", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setIcon(icon31)
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionPrint = QtGui.QAction(MainWindow)
        self.actionPrint.setIcon(icon)
        self.actionPrint.setText(QtGui.QApplication.translate("MainWindow", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionModel_View = QtGui.QAction(MainWindow)
        self.actionModel_View.setCheckable(True)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/3D object.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionModel_View.setIcon(icon33)
        self.actionModel_View.setText(QtGui.QApplication.translate("MainWindow", "Model View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModel_View.setObjectName(_fromUtf8("actionModel_View"))
        self.actionToolbar = QtGui.QAction(MainWindow)
        self.actionToolbar.setCheckable(True)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Tools.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionToolbar.setIcon(icon34)
        self.actionToolbar.setText(QtGui.QApplication.translate("MainWindow", "Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToolbar.setObjectName(_fromUtf8("actionToolbar"))
        self.actionSlice_Inspector = QtGui.QAction(MainWindow)
        self.actionSlice_Inspector.setCheckable(True)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Layers.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSlice_Inspector.setIcon(icon35)
        self.actionSlice_Inspector.setText(QtGui.QApplication.translate("MainWindow", "Slice Inspector", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSlice_Inspector.setObjectName(_fromUtf8("actionSlice_Inspector"))
        self.actionModel_Edit = QtGui.QAction(MainWindow)
        self.actionModel_Edit.setCheckable(True)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Cartesian.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionModel_Edit.setIcon(icon36)
        self.actionModel_Edit.setText(QtGui.QApplication.translate("MainWindow", "Model Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModel_Edit.setObjectName(_fromUtf8("actionModel_Edit"))
        self.actionPreferences_2 = QtGui.QAction(MainWindow)
        self.actionPreferences_2.setIcon(icon26)
        self.actionPreferences_2.setText(QtGui.QApplication.translate("MainWindow", "Preferences...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences_2.setObjectName(_fromUtf8("actionPreferences_2"))
        self.actionPreSlice = QtGui.QAction(MainWindow)
        self.actionPreSlice.setCheckable(True)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Objects.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreSlice.setIcon(icon37)
        self.actionPreSlice.setText(QtGui.QApplication.translate("MainWindow", "Pre-slicing", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreSlice.setObjectName(_fromUtf8("actionPreSlice"))
        self.actionPostSlice = QtGui.QAction(MainWindow)
        self.actionPostSlice.setCheckable(True)
        self.actionPostSlice.setIcon(icon35)
        self.actionPostSlice.setText(QtGui.QApplication.translate("MainWindow", "Post-slicing", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPostSlice.setObjectName(_fromUtf8("actionPostSlice"))
        self.actionSlice = QtGui.QAction(MainWindow)
        self.actionSlice.setIcon(icon8)
        self.actionSlice.setText(QtGui.QApplication.translate("MainWindow", "Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSlice.setToolTip(QtGui.QApplication.translate("MainWindow", "Slice Model", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSlice.setObjectName(_fromUtf8("actionSlice"))
        self.actionAdd_Model = QtGui.QAction(MainWindow)
        self.actionAdd_Model.setIcon(icon33)
        self.actionAdd_Model.setText(QtGui.QApplication.translate("MainWindow", "Add Model", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Model.setObjectName(_fromUtf8("actionAdd_Model"))
        self.actionRemove_Model = QtGui.QAction(MainWindow)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(_fromUtf8(":/_icons/icons/printer/Delete.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove_Model.setIcon(icon38)
        self.actionRemove_Model.setText(QtGui.QApplication.translate("MainWindow", "Remove Model", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_Model.setObjectName(_fromUtf8("actionRemove_Model"))
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionHelp)
        self.menuTools.addAction(self.actionConnect_To_Printer_2)
        self.menuTools.addAction(self.actionOpen_manual_printer_control)
        self.menuTools.addAction(self.actionSlice)
        self.menuTools.addAction(self.actionFirmware_Configurator)
        self.menuTools.addAction(self.actionSave_current_settings_as_default)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuWindow.addAction(self.actionToolbar)
        self.menuWindow.addAction(self.actionModel_View)
        self.menuWindow.addAction(self.actionModel_Edit)
        self.menuWindow.addAction(self.actionSlice_Inspector)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionPreferences_2)
        self.menuEdit.addAction(self.actionAdd_Model)
        self.menuEdit.addAction(self.actionRemove_Model)
        self.menuShow_Workspace.addAction(self.actionPreSlice)
        self.menuShow_Workspace.addAction(self.actionPostSlice)
        self.menuWindow_2.addAction(self.menuShow_Workspace.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuWindow_2.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionConnect_To_Printer_2)
        self.toolBar.addAction(self.actionOpen_manual_printer_control)
        self.toolBar.addAction(self.actionSet_Model_Opacity)
        self.toolBar.addAction(self.actionPreferences)
        self.toolBar_3.addAction(self.actionPreSlice)
        self.toolBar_3.addAction(self.actionPostSlice)
        self.toolBar_3.addSeparator()
        self.toolBar_3.addAction(self.actionSlice)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.actionOpen, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.OpenPrintJob)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.openaboutdialog)
        QtCore.QObject.connect(self.actionHelp, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.openhelp)
        QtCore.QObject.connect(self.actionNext_Slice, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.IncrementSlicingPlanePositive)
        QtCore.QObject.connect(self.actionPrevious_Slice, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.IncrementSlicingPlaneNegative)
        QtCore.QObject.connect(self.actionSet_Model_Opacity, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.UpdateModelOpacityPre)
        QtCore.QObject.connect(self.actionPreferences, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.OpenSettingsDialog)
        QtCore.QObject.connect(self.actionGo_To_Layer, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.GoToLayer)
        QtCore.QObject.connect(self.actionOpen_manual_printer_control, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.openmanualcontrol)
        QtCore.QObject.connect(self.actionConnect_To_Printer_2, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.ConnectToPrinter)
        QtCore.QObject.connect(self.actionFirst_Slice, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.GoToFirstLayer)
        QtCore.QObject.connect(self.actionLast_Slice, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.GoToLastLayer)
        QtCore.QObject.connect(self.actionPostSlice, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.ChangeWorkspacePostSlice)
        QtCore.QObject.connect(self.actionPreSlice, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.ChangeWorkspacePreSlice)
        QtCore.QObject.connect(self.addModel, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.AddModel)
        QtCore.QObject.connect(self.modelList, QtCore.SIGNAL(_fromUtf8("currentItemChanged(QListWidgetItem*,QListWidgetItem*)")), MainWindow.ModelIndexChanged)
        QtCore.QObject.connect(self.scale, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), MainWindow.UpdateScale)
        QtCore.QObject.connect(self.rotationZ, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), MainWindow.UpdateRotationZ)
        QtCore.QObject.connect(self.rotationY, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), MainWindow.UpdateRotationY)
        QtCore.QObject.connect(self.rotationX, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), MainWindow.UpdateRotationX)
        QtCore.QObject.connect(self.positionX, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), MainWindow.UpdatePositionX)
        QtCore.QObject.connect(self.positionY, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), MainWindow.UpdatePositionY)
        QtCore.QObject.connect(self.positionZ, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), MainWindow.UpdatePositionZ)
        QtCore.QObject.connect(self.actionSlice, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.SliceModel)
        QtCore.QObject.connect(self.toolButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.GoToFirstLayer)
        QtCore.QObject.connect(self.toolButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.GoToLastLayer)
        QtCore.QObject.connect(self.toolButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.IncrementSlicingPlaneNegative)
        QtCore.QObject.connect(self.toolButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.IncrementSlicingPlanePositive)
        QtCore.QObject.connect(self.actionSave_As, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.SavePrintJobAs)
        QtCore.QObject.connect(self.actionSave, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.SavePrintJob)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Slice List", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Current Slice", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc
