# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsdialog.ui'
#
# Created: Sun Nov 18 23:55:00 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(659, 329)
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_19 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Printing Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.enableprintercontrol = QtGui.QCheckBox(self.groupBox_2)
        self.enableprintercontrol.setText(QtGui.QApplication.translate("Dialog", "Enable Printer Control?", None, QtGui.QApplication.UnicodeUTF8))
        self.enableprintercontrol.setChecked(False)
        self.enableprintercontrol.setObjectName(_fromUtf8("enableprintercontrol"))
        self.verticalLayout.addWidget(self.enableprintercontrol)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radio_arduinoUno = QtGui.QRadioButton(self.groupBox_2)
        self.radio_arduinoUno.setText(QtGui.QApplication.translate("Dialog", "Arduino Uno", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_arduinoUno.setChecked(True)
        self.radio_arduinoUno.setObjectName(_fromUtf8("radio_arduinoUno"))
        self.horizontalLayout_4.addWidget(self.radio_arduinoUno)
        self.radio_arduinoMega = QtGui.QRadioButton(self.groupBox_2)
        self.radio_arduinoMega.setText(QtGui.QApplication.translate("Dialog", "Arduino Mega", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_arduinoMega.setObjectName(_fromUtf8("radio_arduinoMega"))
        self.horizontalLayout_4.addWidget(self.radio_arduinoMega)
        self.radio_pyMCU = QtGui.QRadioButton(self.groupBox_2)
        self.radio_pyMCU.setText(QtGui.QApplication.translate("Dialog", "PyMCU", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_pyMCU.setObjectName(_fromUtf8("radio_pyMCU"))
        self.horizontalLayout_4.addWidget(self.radio_pyMCU)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_29 = QtGui.QLabel(self.groupBox_2)
        self.label_29.setText(QtGui.QApplication.translate("Dialog", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_3.addWidget(self.label_29)
        self.pickcom = QtGui.QComboBox(self.groupBox_2)
        self.pickcom.setObjectName(_fromUtf8("pickcom"))
        self.horizontalLayout_3.addWidget(self.pickcom)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setText(QtGui.QApplication.translate("Dialog", "Baud:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_3.addWidget(self.label_24)
        self.printerbaud = QtGui.QComboBox(self.groupBox_2)
        self.printerbaud.setObjectName(_fromUtf8("printerbaud"))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(0, QtGui.QApplication.translate("Dialog", "115200", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(1, QtGui.QApplication.translate("Dialog", "57600", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(2, QtGui.QApplication.translate("Dialog", "38400", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(3, QtGui.QApplication.translate("Dialog", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(4, QtGui.QApplication.translate("Dialog", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(5, QtGui.QApplication.translate("Dialog", "4800", None, QtGui.QApplication.UnicodeUTF8))
        self.printerbaud.addItem(_fromUtf8(""))
        self.printerbaud.setItemText(6, QtGui.QApplication.translate("Dialog", "2400", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_3.addWidget(self.printerbaud)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Remote Host Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.remote_port = QtGui.QLineEdit(self.groupBox_2)
        self.remote_port.setEnabled(False)
        self.remote_port.setText(_fromUtf8(""))
        self.remote_port.setObjectName(_fromUtf8("remote_port"))
        self.horizontalLayout_5.addWidget(self.remote_port)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Exposure Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_20.addWidget(self.label_6)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.exposure_time = QtGui.QLineEdit(self.groupBox_2)
        self.exposure_time.setText(_fromUtf8(""))
        self.exposure_time.setObjectName(_fromUtf8("exposure_time"))
        self.horizontalLayout_6.addWidget(self.exposure_time)
        self.label_28 = QtGui.QLabel(self.groupBox_2)
        self.label_28.setText(QtGui.QApplication.translate("Dialog", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_6.addWidget(self.label_28)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_26 = QtGui.QLabel(self.groupBox_2)
        self.label_26.setText(QtGui.QApplication.translate("Dialog", "Number of starting layers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_8.addWidget(self.label_26)
        self.starting_layers = QtGui.QLineEdit(self.groupBox_2)
        self.starting_layers.setText(_fromUtf8(""))
        self.starting_layers.setObjectName(_fromUtf8("starting_layers"))
        self.horizontalLayout_8.addWidget(self.starting_layers)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_27 = QtGui.QLabel(self.groupBox_2)
        self.label_27.setText(QtGui.QApplication.translate("Dialog", "Starting layer exposure ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_9.addWidget(self.label_27)
        self.starting_layer_exposure = QtGui.QLineEdit(self.groupBox_2)
        self.starting_layer_exposure.setText(_fromUtf8(""))
        self.starting_layer_exposure.setObjectName(_fromUtf8("starting_layer_exposure"))
        self.horizontalLayout_9.addWidget(self.starting_layer_exposure)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.enableslideshow = QtGui.QCheckBox(self.groupBox_2)
        self.enableslideshow.setText(QtGui.QApplication.translate("Dialog", "Slideshow enabled?", None, QtGui.QApplication.UnicodeUTF8))
        self.enableslideshow.setChecked(False)
        self.enableslideshow.setObjectName(_fromUtf8("enableslideshow"))
        self.verticalLayout.addWidget(self.enableslideshow)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_25 = QtGui.QLabel(self.groupBox_2)
        self.label_25.setText(QtGui.QApplication.translate("Dialog", "Choose monitor to print on:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_10.addWidget(self.label_25)
        self.pickscreen = QtGui.QComboBox(self.groupBox_2)
        self.pickscreen.setObjectName(_fromUtf8("pickscreen"))
        self.horizontalLayout_10.addWidget(self.pickscreen)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Slicing Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Image Height", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_8.addWidget(self.label_7)
        self.image_height = QtGui.QLineEdit(self.groupBox)
        self.image_height.setText(_fromUtf8(""))
        self.image_height.setObjectName(_fromUtf8("image_height"))
        self.verticalLayout_8.addWidget(self.image_height)
        self.horizontalLayout_12.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Image Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_9.addWidget(self.label_8)
        self.image_width = QtGui.QLineEdit(self.groupBox)
        self.image_width.setText(_fromUtf8(""))
        self.image_width.setObjectName(_fromUtf8("image_width"))
        self.verticalLayout_9.addWidget(self.image_width)
        self.horizontalLayout_12.addLayout(self.verticalLayout_9)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Layer Thickness", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_10.addWidget(self.label_9)
        self.layer_thickness = QtGui.QLineEdit(self.groupBox)
        self.layer_thickness.setText(_fromUtf8(""))
        self.layer_thickness.setObjectName(_fromUtf8("layer_thickness"))
        self.verticalLayout_10.addWidget(self.layer_thickness)
        self.horizontalLayout_13.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Slicing Plane", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_11.addWidget(self.label_10)
        self.slicing_plane = QtGui.QComboBox(self.groupBox)
        self.slicing_plane.setObjectName(_fromUtf8("slicing_plane"))
        self.slicing_plane.addItem(_fromUtf8(""))
        self.slicing_plane.setItemText(0, QtGui.QApplication.translate("Dialog", "XZ", None, QtGui.QApplication.UnicodeUTF8))
        self.slicing_plane.addItem(_fromUtf8(""))
        self.slicing_plane.setItemText(1, QtGui.QApplication.translate("Dialog", "XY", None, QtGui.QApplication.UnicodeUTF8))
        self.slicing_plane.addItem(_fromUtf8(""))
        self.slicing_plane.setItemText(2, QtGui.QApplication.translate("Dialog", "YZ", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_11.addWidget(self.slicing_plane)
        self.horizontalLayout_13.addLayout(self.verticalLayout_11)
        self.verticalLayout_13.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Starting Depth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_14.addWidget(self.label_13)
        self.z_options_start = QtGui.QLineEdit(self.groupBox)
        self.z_options_start.setText(_fromUtf8(""))
        self.z_options_start.setObjectName(_fromUtf8("z_options_start"))
        self.horizontalLayout_14.addWidget(self.z_options_start)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_22 = QtGui.QLabel(self.groupBox)
        self.label_22.setText(QtGui.QApplication.translate("Dialog", "Ending Depth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_15.addWidget(self.label_22)
        self.z_options_end = QtGui.QLineEdit(self.groupBox)
        self.z_options_end.setText(_fromUtf8(""))
        self.z_options_end.setObjectName(_fromUtf8("z_options_end"))
        self.horizontalLayout_15.addWidget(self.z_options_end)
        self.verticalLayout_13.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_23 = QtGui.QLabel(self.groupBox)
        self.label_23.setText(QtGui.QApplication.translate("Dialog", "Z slicing increment:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_16.addWidget(self.label_23)
        self.z_options_increment = QtGui.QLineEdit(self.groupBox)
        self.z_options_increment.setText(_fromUtf8(""))
        self.z_options_increment.setObjectName(_fromUtf8("z_options_increment"))
        self.horizontalLayout_16.addWidget(self.z_options_increment)
        self.verticalLayout_13.addLayout(self.horizontalLayout_16)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setText(QtGui.QApplication.translate("Dialog", "File to Slice:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_12.addWidget(self.label)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.displayfilenamelabel = QtGui.QLineEdit(self.groupBox)
        self.displayfilenamelabel.setText(_fromUtf8(""))
        self.displayfilenamelabel.setReadOnly(False)
        self.displayfilenamelabel.setObjectName(_fromUtf8("displayfilenamelabel"))
        self.horizontalLayout_17.addWidget(self.displayfilenamelabel)
        self.toolButton = QtGui.QToolButton(self.groupBox)
        self.toolButton.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_17.addWidget(self.toolButton)
        self.verticalLayout_12.addLayout(self.horizontalLayout_17)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.verticalLayout_13)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Projector Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.projectorcontrol = QtGui.QCheckBox(self.groupBox_3)
        self.projectorcontrol.setText(QtGui.QApplication.translate("Dialog", "Enable Projector Control?", None, QtGui.QApplication.UnicodeUTF8))
        self.projectorcontrol.setChecked(False)
        self.projectorcontrol.setObjectName(_fromUtf8("projectorcontrol"))
        self.verticalLayout_6.addWidget(self.projectorcontrol)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "COM Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_5.addWidget(self.label_16)
        self.projector_pickcom = QtGui.QComboBox(self.groupBox_3)
        self.projector_pickcom.setObjectName(_fromUtf8("projector_pickcom"))
        self.verticalLayout_5.addWidget(self.projector_pickcom)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Serial Baud rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_14.addWidget(self.label_17)
        self.projector_baud = QtGui.QComboBox(self.groupBox_3)
        self.projector_baud.setObjectName(_fromUtf8("projector_baud"))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(0, QtGui.QApplication.translate("Dialog", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(1, QtGui.QApplication.translate("Dialog", "115200", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(2, QtGui.QApplication.translate("Dialog", "57600", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(3, QtGui.QApplication.translate("Dialog", "38400", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(4, QtGui.QApplication.translate("Dialog", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(5, QtGui.QApplication.translate("Dialog", "4800", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_baud.addItem(_fromUtf8(""))
        self.projector_baud.setItemText(6, QtGui.QApplication.translate("Dialog", "2400", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_14.addWidget(self.projector_baud)
        self.horizontalLayout_11.addLayout(self.verticalLayout_14)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Parity:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_15.addWidget(self.label_18)
        self.projector_parity = QtGui.QComboBox(self.groupBox_3)
        self.projector_parity.setObjectName(_fromUtf8("projector_parity"))
        self.projector_parity.addItem(_fromUtf8(""))
        self.projector_parity.setItemText(0, QtGui.QApplication.translate("Dialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_parity.addItem(_fromUtf8(""))
        self.projector_parity.setItemText(1, QtGui.QApplication.translate("Dialog", "Even", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_parity.addItem(_fromUtf8(""))
        self.projector_parity.setItemText(2, QtGui.QApplication.translate("Dialog", "Odd", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_parity.addItem(_fromUtf8(""))
        self.projector_parity.setItemText(3, QtGui.QApplication.translate("Dialog", "Mark", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_parity.addItem(_fromUtf8(""))
        self.projector_parity.setItemText(4, QtGui.QApplication.translate("Dialog", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_15.addWidget(self.projector_parity)
        self.horizontalLayout_18.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Data Bits:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_16.addWidget(self.label_19)
        self.projector_databits = QtGui.QComboBox(self.groupBox_3)
        self.projector_databits.setObjectName(_fromUtf8("projector_databits"))
        self.projector_databits.addItem(_fromUtf8(""))
        self.projector_databits.setItemText(0, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_databits.addItem(_fromUtf8(""))
        self.projector_databits.setItemText(1, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_databits.addItem(_fromUtf8(""))
        self.projector_databits.setItemText(2, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_databits.addItem(_fromUtf8(""))
        self.projector_databits.setItemText(3, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_16.addWidget(self.projector_databits)
        self.horizontalLayout_18.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "Stop Bits:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_17.addWidget(self.label_20)
        self.projector_stopbits = QtGui.QComboBox(self.groupBox_3)
        self.projector_stopbits.setObjectName(_fromUtf8("projector_stopbits"))
        self.projector_stopbits.addItem(_fromUtf8(""))
        self.projector_stopbits.setItemText(0, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.projector_stopbits.addItem(_fromUtf8(""))
        self.projector_stopbits.setItemText(1, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_17.addWidget(self.projector_stopbits)
        self.horizontalLayout_18.addLayout(self.verticalLayout_17)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "Power Off Command:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_18.addWidget(self.label_21)
        self.projector_poweroffcommand = QtGui.QLineEdit(self.groupBox_3)
        self.projector_poweroffcommand.setText(_fromUtf8(""))
        self.projector_poweroffcommand.setObjectName(_fromUtf8("projector_poweroffcommand"))
        self.verticalLayout_18.addWidget(self.projector_poweroffcommand)
        self.verticalLayout_6.addLayout(self.verticalLayout_18)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setText(QtGui.QApplication.translate("Dialog", "Apply Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_3 = QtGui.QPushButton(Dialog)
        self.pushButton_3.setText(QtGui.QApplication.translate("Dialog", "Save Settings to Config File", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtGui.QPushButton(Dialog)
        self.pushButton_2.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_19.addLayout(self.verticalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        pass

